config/routes.rb
Rails.application.routes.draw do

  get 'your_orders' => 'orders#your_orders'

  post 'add_to_cart' => 'cart#add_to_cart'

  post 'order_complete' => 'cart#order_complete'

  post 'cancel_checkout' => 'cart#cancel_checkout'

  delete 'delete_from_cart' => 'cart#delete_from_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  devise_for :users
  get 'categorical' => 'storefront#items_by_category'

  get 'branding' => 'storefront#items_by_brand'

  resources :categories
  resources :products

  root 'storefront#all_items'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  before_action :authenticate_user!, only: [:checkout]

  def add_to_cart
    @order = current_order

  	line_item = @order.line_items.new(product_id: params[:product_id], quantity: params[:quantity])

    if line_item.quantity.nil?
      flash[:error] = "Select any quantity for the product #{line_item.product.name} you want to buy!"
      line_item.destroy
      redirect_to root_url
    else
     @order.save
     session[:order_id] = @order.id
  	 line_item.update(line_item_total: (line_item.quantity * line_item.product.price))
  	 redirect_to root_url
    end
  end

  def delete_from_cart
  	line_item = LineItem.find(params[:line_item_id])
  	line_item.destroy

  	redirect_to view_order_path
  end

  def cancel_checkout
    order = Order.find(params[:order_id])
    session[:order_id] = nil
    order.destroy

    redirect_to root_url
  end

  def view_order
  	@line_items = current_order.line_items
  end

  def checkout
    line_items = current_order.line_items
    if line_items.empty? 
        redirect_to root_url
    else
      @order = current_order
      @order.update(user_id: current_user.id, subtotal: 0)
        line_items.each do |line_item|
            if @order.order_items[line_item.product_id].nil?
                @order.order_items[line_item.product_id] = line_item.quantity
            elsif @order.order_items[line_item.id] == line_item.id
                @order.order_items[line_item.product_id] += line_item.quantity
            end
            @order.subtotal += line_item.line_item_total
     
        end
      
        @order.save
        @order.update(sales_tax: (@order.subtotal * 0.08))
        @order.update(grand_total: (@order.sales_tax + @order.subtotal))
     end

  end

  def order_complete
       # Amount in cents
       line_items = current_order.line_items

       @order = Order.find(params[:order_id])
       @amount = (@order.grand_total.to_f.round(2) * 100).to_i

      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => 'Tech Talent Store Customer',
        :currency    => 'usd'
      )

      session[:order_id] = nil
      line_items.destroy_all

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to root_url
  end

end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/checkout.html.erb
<h3>Thanks for shopping with us!</h3>
<h4>Your Order:</h4>

<table class="table">
	<thead>
		<tr>
			<th>Product</th>
			<th>Quantity</th>
			<th>Unit Price</th>
			<th>Total Price</th>
		</tr>
	</thead>
	<tbody>
		<% @order.order_items.each do |key, value| %>
			<tr>
				<td><%= Product.find(key).name %></td>
				<td><%= value %></td>
				<td><%= number_to_currency Product.find(key).price %></td>
				<td><%= number_to_currency Product.find(key).price * value %></td>
			</tr>
		<% end %>
	</tbody>
</table>




<p>
	<strong>Subtotal:</strong><%= number_to_currency @order.subtotal %>
</p>
<p>
	<strong>Tax Total:</strong><%= number_to_currency @order.sales_tax %>
</p>
<p>
	<strong>Order Total:</strong><%= number_to_currency @order.grand_total %>
</p>

<div style="display:inline-block;">
	<%= form_tag cancel_checkout_path, method: :post do %>
		<%= hidden_field_tag :order_id, @order.id %>
		<%= submit_tag "Empty Cart", class: "btn btn-danger", data: {
			confirm: "Are You Sure?" } %> 
	<% end %>
</div>

<div style="display:inline-block;">
	<%= form_tag order_complete_path do %>
		<div>
			<%= hidden_field_tag :order_id, @order.id %>
		</div>
		<script src="https://checkout.stripe.com/checkout.js"
		class="stripe-button"
		data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
		data-description="Order <%= @order.id %>"
		data-amount="<%= (@order.grand_total.to_f.round(2) * 100) %>"></script>
	<% end %>
</div>

app/views/cart/order_complete.html.erb
<h2>Thank you for your order!</h2>

<h4>
  <p><strong>Order #<%= @order.id %> will be shipping to you, <%= @order.user.email %>, as soon as possible!</strong></p>
</h4>

app/views/cart/view_order.html.erb
<h2>Your Shopping Cart</h2>

<div>
	<table class="table">
		<thead>
			<tr>
				<th>Product</th>
				<th>Unit Price</th>
				<th>Quantity</th>
				<th>Total Price</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @line_items.each do |line_item| %>
				<tr>
					<td><%= line_item.product.name %></td>
					<td><%= number_to_currency line_item.product.price %></td>
					<td><%= line_item.quantity %></td>
					<td><%= number_to_currency line_item.line_item_total %></td>
					<td><%= form_tag delete_from_cart_path, method: :delete do %>
						 <%= hidden_field_tag :line_item_id, line_item.id %>
						 <%= submit_tag "Delete Item", class: "btn btn-danger", data: { confirm: "Are You Sure?"} %>
						<% end %>
					</td>
				</tr>
			<% end %>
		</tbody>

	</table>
</div>

<% unless @line_items.blank? %>
<%= link_to "Proceed To Checkout", checkout_path, class: "btn btn-success" %>
<% end %>


<%= link_to "Continue Shopping", root_path, class: "btn btn-info" %>