config/routes.rb
Rails.application.routes.draw do

  get 'your_orders' => 'orders#your_orders'

  post 'add_to_cart' => 'cart#add_to_cart'

  post 'order_complete' => 'cart#order_complete'

  post 'cancel_checkout' => 'cart#cancel_checkout'

  delete 'delete_from_cart' => 'cart#delete_from_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  devise_for :users
  get 'categorical' => 'storefront#items_by_category'

  get 'branding' => 'storefront#items_by_brand'

  resources :categories
  resources :products

  root 'storefront#all_items'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Tech Talent Store', root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">

      <!-- categories dropdown -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Find By Category<span class="caret"></span></a>
          <ul class="dropdown-menu">
           <% @categories.each do |category| %>
              <li><%= link_to category.name, categorical_path(cat_id: category.id) %></li>
           <% end %>
          </ul>
        </li>
        <!-- end categories dropdown -->


      <!-- brands dropdown -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Find By Brand<span class="caret"></span></a>
          <ul class="dropdown-menu">
           <% @brands.each do |brand| %>
              <li><%= link_to brand, branding_path(brand: brand) %></li>
           <% end %>
          </ul>
        </li>
        <!-- end brands dropdown -->
      </ul>


      <ul class="nav navbar-nav navbar-right">
            <!-- admin dropdown -->
      <% if signed_in? && current_user.role == "admin" %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin<span class="caret"></span></a>
          <ul class="dropdown-menu">
              <li><%= link_to "Categories", categories_path %></li>
              <li><%= link_to "Productss", products_path %></li>
          </ul>
        </li>
        <% end %>
        <!-- end admin dropdown -->
        <li><%= link_to "My Cart (#{@line_items.sum('quantity')})", view_order_path %></li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= image_tag "TTS.png", size: 25 %><span class="caret"></span></a>
            <ul class="dropdown-menu">
        <% if current_user %>
          <li><%= link_to 'My Orders', your_orders_path %></li>
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %> 
          </ul>
        </li>
       
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/navbar' %>
    
    <div id="flash">
      <% flash.each do |type, message| %>
        <div class="alert <%= bootstrap_class_for(type)%> fade-in">
          <button class="close" data-dismiss="alert">X</button>
          <%= message %>
        </div>
      <% end %>
    </div>

  	<div class="container">
    	<%= yield %>
    </div>
  </body>
</html>